### ISSUE TITLE
Swagger UI

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#114]
**Technical Description**
Initialize Swagger UI with path `/docs`

**Acceptance Criteria**
- Program should server Swagger UI when program receive request into URL `/docs`

**Technical type** :  🦌 New Feature

**Task** :
- [x] Install Swagger UI
- [x] Implement Swagger as handler 
- [x] Construct OpenAPI Swagger
