### ISSUE TITLE
Construct JSON Response

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#115]
**Technical Description**
Research how to construct JSON Response, include success response and error response 

**Acceptance Criteria**
- Section` JSON Response` should present on README file

**Technical type** :  🦧 Documentation content changes

**Task** :
- [x] How to construct base response on go
- [x] Best way to build success response 
- [x] Best way to build error response include message, error code, HTTP code, etc
