### ISSUE TITLE
Setup Middleware

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#118]
**Technical Description**
Initialize middle-ware server such as 404 Page, Compression, Transaction ID, Request ID, and swagger UI

**Acceptance Criteria**
- `middleware.go `should present on internal directory
- `middleware` package should present on `middleware.go` files

**Technical type** :  🐞 Possible Bug

**Task** :
- [x] 404 Page Not found
- [x] RequestID middle-ware
- [x] Swagger UI as a middle-ware
- [x] TransactionID middle-ware
- [x] Recover middleware
- [x] Response Time middleware
- [x] Implement Logger
- [x] Implement config ENV
