### ISSUE TITLE
Password Hasing

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#132]
**Technical Description**
Spike password hashing like argon2ID, bcrypt, etc, how they work, how to implement it, how it benchmark and how to save those hashing format into database 

**Acceptance Criteria**
- No acceptance criteria required

**Technical type** :  🦧 Documentation content changes

**Task** :
- [x] How they work
- [x] How to implement it 
- [x] Hows their benchmark
- [x] How to save thier hashing format into database
