### ISSUE TITLE
SQL Database Setup

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#154]
**Technical Description**
Initialize SQL database, and init package with Postgress SQL

**Acceptance Criteria**
- SQL Postgress should present on `go.mod` and `go.sum` files
- Package database should present on the project

**Technical type** :  🐞 Possible Bug

**Task** :
- [x] install pstgress SQL
- [x] init package database 
- [x] init sql transaction interface
- [x] implement sql transaction
- [x] implement ENV 
- [x] Implement Timeout
