### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#191]
**Technical Description**
Initialize GitHub action that perform `go test`, `code coverage` and `go build` with multiple operating system (windows, linux, and mac os) matrix.

**Acceptance Criteria**
- GitHub action should use at lease 1.16 go version 
- GitHub action should use `ubuntu-latest` as container operating system
- GitHub action should run when pull request open
- GitHub action should run when there is changes on branch
- GitHub action should produce test report and code coverage in text base file
- GitHub action should display those test report and code coverage in pull request comment  
- GitHub action should fail when code coverage bellow 50%

**Technical type** :  
- 🦌 New Feature
- 🏅 Build related changes

**Task** :
- [x] Init workflow yaml
- [x] Setup Go
- [x] Setup unit testing job
- [x] Setup code coverage job
- [x] Display test report and code coverage in pull request comment
- [x] #322
- [ ] #323
