### ISSUE TITLE
GitHub Authentication

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#341]
**User story**
> ``As a [type of user], I want [an action] so that [a benefit/a value]``

***As a*** developer who use AAA service to authenticate user, ***i want*** use GitHub Authentication service ***so that*** i can use those return GitHub authentication token to  authenticate user and generate zephryone JWT tokens

**Acceptance Criteria**
- Should be able to send GitHub Authentication request
- Should be able to save GitHub ID on zephryone database 
- Should be able to save GitHub user info on zephryone database 
- Should return a JSON object with field **access_token** and **refresh_token**

**Non-Functional Requirements**
- The API should support a load of 50 API requests per second without failing.
- API should process the request and respond within maximum 10 seconds in a cloud-to-cloud setup.
- API between zephryone and GitHub sever should be processed within less than 1000ms.

**Issue type** :  🦌 New Feature

**Descriptions** :  
*No description needed*

**Task** :
- [ ] Research GitHub Authentication
- [ ] Create `external_auth` table
- [ ] Create endpoint to authenticate user via external authentication service
