### ISSUE TITLE
Golang Project Setup

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#45]
**Technical Description**
Initialize GO modules to defines the module’s module path, which is also the import path used for the root directory, and its dependency requirements, which are the other modules needed for a successful build. Each dependency requirement is written as a module path and a specific semantic version.

**Acceptance Criteria**
- `go.mod` and `go.sum` files should present on root directory
- env example should present on root directory and contain prefix ZO on every variable

**Technical type** :  🦌 New Feature

**Task** :
- [x] Init GO Modules
- [x] Set main function
- [x] Init Go server
- [x] Create folder structure
- [x] Init ENV
