### ISSUE TITLE
Migrate Zap Logger to Zerolog

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#69]
**Technical Description**
Remove current logger system which is **_zap logger_** and replace it with [zerolog](https://zerolog.io/). I conside zerolog because it have a better performance than zap logger based on this benchmark:
![image](https://user-images.githubusercontent.com/65327739/117576390-04059580-b110-11eb-8ebd-155edf434dd4.png)

and also zero logger have better prettier print on console and easy to structure logging with custom field 
![image](https://user-images.githubusercontent.com/65327739/117576460-4fb83f00-b110-11eb-8e25-d6026943309f.png)

**Acceptance Criteria**
- Zerolog dependency present on `go.mod` and `go.sum` files
- Zerolog should be create structured logging
- Zerolog should be provide pretty log

**Technical type** :  
- [x] 🦌 New Feature
- [x] 🏇🏼 Refactoring (no functional changes, no api changes)
- [x] 🦧 Documentation content changes

**Task** :
- [x] Install Zerolog
- [x] Implement Zerolog and remove Zap Logger
- [x] Update README
