### ISSUE TITLE
Refactor how to initialize log for every package

### ISSUE THREAD

**Issue by rasatmaja** [rasatmaja/zephyr-one#72]
**Technical Description**
Refactor how to initialize log for every package. The purpose of this refactoring is to reduce setter function for logger for every package that need logger. 
```
// setup handler
handler := handler.New()
handler.SetLogger(log)
```
 
**Acceptance Criteria**
- logger setter function on package server and handler should be gone 

**Technical type** :  🏇🏼 Refactoring (no functional changes, no api changes)

**Task** :
- [x] Remove logger setter function in handler
- [x] Init logger when package initialize (on `New` function)
- [x] Remove app field logger
- [x] Remove Sync function
- [x] Create function log fLog
- [x] Implement singleton patter when init logger
